export enum SocketEvents {
  NEW_MESSAGE = 'NEW_MESSAGE',
  REQUEST_ROOMS = 'REQUEST_ROOMS',
  CREATE_ROOM = 'CREATE_ROOM',
  JOIN_ROOM = 'JOIN_ROOM',
  LEAVE_ROOM = 'LEAVE_ROOM',
  REQUEST_GAME = 'REQUEST_GAME',

  GAME = 'GAME',
  ROOMS = 'ROOMS',
  MESSAGES = 'MESSAGES',
}
